<template lang="pug">
.layout-landing.hero.is-fullheight(flex="column align-stretch")
  header.navbar.card
    .container
      .navbar-brand
        router-link.navbar-item(to="/")
          i.icon-home Home
        .navbar-burger.burger(@click="toggleMenu()")
          span(v-for="i in 3")

      .navbar-menu(:class="{'is-active': showMobileMenu}")
        slot(name="top-menu")

  section.content-main(flex-item="grow-1")
    slot
      blockquote.
        In online marketing, a landing page, sometimes known as a "lead capture page" or a "lander", or a "destination page", is a single web page that appears in response to clicking on a search engine optimized search result or an online advertisement. The landing page will usually display directed sales copy that is a logical extension of the advertisement, search result or link. Landing pages are used for lead generation. The actions that a visitor takes on a landing page is what determines an advertiser's conversion rate.

        Landing pages are often linked to social media, e-mail campaigns or search engine marketing campaigns in order to enhance the effectiveness of the advertisements. The general goal of a landing page is to convert site visitors into sales or leads. If the goal is to obtain a lead, the landing page will include some method for the visitor to get into contact with the company, usually a phone number, or an inquiry form. If a sale is required, the landing page will usually have a link for the visitor to click, which will then send them to a shopping cart or a checkout area. By analyzing activity generated by the linked URL, marketers can use click-through rates and conversion rate to determine the success of an advertisement

  footer.footer.hide-if-empty
    slot(name="footer")
</template>

<script>

export default {
  data() {
    return {
      showMobileMenu: false,
    }
  },
  name: 'landing-layout',
  methods: {
    toggleMenu() {
      this.showMobileMenu = !this.showMobileMenu
    },
  },
  computed: { },
  components: { },
}
</script>

<style lang="scss" scoped>

.navbar {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  z-index: 10;
}

.content-main {
  padding-top: $navbar-height;
}
</style>
