# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/project/vue
  docker:
    - image: circleci/node:6-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      - run: npm install

      - run: ./node_modules/.bin/rimraf public

      - persist_to_workspace:
          root: ~/project
          paths:
            - vue


  build:client:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: npm run build:client

  build:server:
    <<: *defaults
    steps:
      - checkout
      - run: npm run build:server

  build:ssr:
    <<: *defaults
    steps:
      - checkout
      - run: npm run build:prerender
      - run: npm run build:functions
      - run: npm run build:storybook

  deploy:
    <<: *defaults
    steps:
      - checkout
      - deploy:
          name: firebase deploy
          command: |
            node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  build_deploy:
    jobs:
      - install
      - build:client:
          requires:
            - install
      - build:server:
          requires:
            - install
      - build:ssr:
          requires:
            - build:client
            - build:server
      - deploy:
          requires:
            - build:ssr
