# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:6-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: ./node_modules/.bin/rimraf public
      - run: pwd
      - persist_to_workspace:
          root: ~/project

  build:client:
    <<: *defaults
    steps:
      - run: npm run build:client

  build:server:
    <<: *defaults
    steps:
      - run: npm run build:server

  build:ssr:
    <<: *defaults
    steps:
      - run: npm run build:prerender
      - run: npm run build:functions
      - run: npm run build:storybook

  deploy:
    <<: *defaults
    steps:
      - deploy:
          name: firebase deploy
          command: |
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  build_deploy:
    jobs:
      - install
      - build:client:
          requires:
            - install
      - build:server:
          requires:
            - install
      - build:ssr:
          requires:
            - build:client
            - build:server
      - deploy:
          requires:
            - build:ssr
